/**
 * @loombox/protocol v1 (SPEC §10, §16; `docs/v1-plan.md`; issue #315).
 * Additive alongside the v0 schema in `../index.ts` — every v0 export stays
 * untouched; this module is the whole v1 wire contract, re-exported from the
 * package root.
 */

export type { Base64String, EncryptedEnvelope, EncryptionAlg } from './envelope';
export { base64String, encryptedEnvelope, encryptionAlg } from './envelope';

export type {
  BaseMessageV1,
  BuildIdentityV1,
  Initialize,
  InitializeResult,
  WireRole,
} from './handshake';
export {
  PROTOCOL_V1,
  SUPPORTED_PROTOCOL_VERSIONS,
  baseMessageV1,
  buildIdentityMismatch,
  buildIdentityV1,
  initialize,
  initializeResult,
  negotiateVersion,
  wireRole,
} from './handshake';

export type {
  AmkEpochFetchRequest,
  AmkEpochFetchResponse,
  AmkEpochPendingEnvelope,
  AmkEscrow,
  DeviceRegister,
  DeviceRevoke,
  DeviceRotate,
  NewDeviceBootstrapRequest,
  NewDeviceBootstrapResponse,
  QrPairingRequest,
  QrPairingResponse,
  WrappedAmkEnvelope,
} from './devices';
export {
  amkEpochFetchRequest,
  amkEpochFetchResponse,
  amkEscrow,
  deviceRegister,
  deviceRevoke,
  deviceRotate,
  newDeviceBootstrapRequest,
  newDeviceBootstrapResponse,
  qrPairingRequest,
  qrPairingResponse,
  wrappedAmkEnvelope,
} from './devices';

export type {
  TargetAnnounce,
  TargetDescriptor,
  TargetHealth,
  TargetKind,
  TargetList,
  TargetListEntry,
  TargetListRequest,
  TargetResourceSample,
  TargetStatus,
} from './targets';
export {
  targetAnnounce,
  targetDescriptor,
  targetHealth,
  targetKind,
  targetList,
  targetListEntry,
  targetListRequest,
  targetResourceSample,
  targetStatus,
} from './targets';

export type {
  SessionAnnounceV1,
  SessionCreate,
  SessionListRequest,
  SessionListV1,
  SessionMetaPublic,
  SessionPrivateMetaV1,
  SessionResume,
  SessionWithPrivateEnvelope,
} from './sessions';
export {
  parseSessionPrivateMetaV1,
  safeParseSessionPrivateMetaV1,
  sessionAnnounceV1,
  sessionCreate,
  sessionListRequest,
  sessionListV1,
  sessionMetaPublic,
  sessionPrivateMetaV1,
  sessionResume,
  sessionWithPrivateEnvelope,
} from './sessions';

export type {
  McpHttpServerConfigV1,
  McpServerConfigV1,
  McpServerVarDeclV1,
  McpSseServerConfigV1,
  McpStdioServerConfigV1,
} from './mcp-servers';
export {
  mcpHttpServerConfigV1,
  mcpServerConfigV1,
  mcpServerVarDeclV1,
  mcpSseServerConfigV1,
  mcpStdioServerConfigV1,
  parseMcpServerConfigV1,
  safeParseMcpServerConfigV1,
} from './mcp-servers';

export type { ProjectEnvVarDeclV1 } from './project-env';
export {
  parseProjectEnvVarDeclV1,
  projectEnvVarDeclV1,
  safeParseProjectEnvVarDeclV1,
} from './project-env';

export type {
  SessionArchiveRequest,
  SessionArchiveResponse,
  SessionArchiveResult,
  SessionForkRequest,
  SessionForkResponse,
  SessionForkResult,
} from './session-lifecycle';
export {
  sessionArchiveRequest,
  sessionArchiveResponse,
  sessionArchiveResult,
  sessionForkRequest,
  sessionForkResponse,
  sessionForkResult,
} from './session-lifecycle';

export type { SessionUpdateEnvelopeV1 } from './transcript';
export { sessionUpdateEnvelopeV1 } from './transcript';

export type {
  AcpAvailableCommandInputV1,
  AcpAvailableCommandV1,
  AcpConfigOptionChoiceV1,
  AcpConfigOptionV1,
  AvailableCommandsUpdateEventV1,
  ConfigOptionsEventV1,
  ConfigOptionUpdateEventV1,
  McpServerFailureCategoryV1,
  McpServerPromptArgumentV1,
  McpServerPromptV1,
  McpServerPromptsEntryV1,
  McpServerPromptsEventV1,
  McpServerStatusEntryV1,
  McpServerStatusEventV1,
  SessionLifecycleEventV1,
  SessionStatusEventV1,
  SessionStatusV1,
  TurnEndedEventV1,
  TurnStartedEventV1,
} from './session-events';
export {
  acpAvailableCommandInputV1,
  acpAvailableCommandV1,
  acpConfigOptionChoiceV1,
  acpConfigOptionV1,
  availableCommandsUpdateEventV1,
  configOptionsEventV1,
  configOptionUpdateEventV1,
  mcpServerFailureCategoryV1,
  mcpServerPromptArgumentV1,
  mcpServerPromptV1,
  mcpServerPromptsEntryV1,
  mcpServerPromptsEventV1,
  mcpServerStatusEntryV1,
  mcpServerStatusEventV1,
  parseSessionLifecycleEventV1,
  safeParseSessionLifecycleEventV1,
  sessionLifecycleEventV1,
  sessionStatusEventV1,
  sessionStatusV1,
  turnEndedEventV1,
  turnStartedEventV1,
} from './session-events';

export type {
  ConfigOption,
  ConfigOptionResult,
  ConfigOptionSetResult,
  PermissionDecision,
  PermissionRequest,
  PermissionResponse,
  PromptInjectV1,
} from './steering';
export {
  configOption,
  configOptionResult,
  configOptionSetResult,
  permissionDecision,
  permissionRequest,
  permissionResponse,
  promptInjectV1,
} from './steering';

export type {
  BlobDownload,
  BlobDownloadResponse,
  BlobRef,
  BlobUpload,
  FileEventPayloadV1,
} from './attachments';
export {
  blobDownload,
  blobDownloadResponse,
  blobRef,
  blobUpload,
  fileEventPayloadV1,
  parseFileEventPayloadV1,
  safeParseFileEventPayloadV1,
} from './attachments';

export type {
  AgentInstructionsFileNameV1,
  AgentInstructionsFileStateV1,
  AgentInstructionsGetRequest,
  AgentInstructionsGetResponse,
  AgentInstructionsGetResponsePayloadV1,
  AgentInstructionsSetRequest,
  AgentInstructionsSetRequestPayloadV1,
  AgentInstructionsSetResponse,
  AgentInstructionsSetResponsePayloadV1,
} from './agent-instructions';
export {
  agentInstructionsFileNameV1,
  agentInstructionsFileStateV1,
  agentInstructionsGetRequest,
  agentInstructionsGetResponse,
  agentInstructionsGetResponsePayloadV1,
  agentInstructionsSetRequest,
  agentInstructionsSetRequestPayloadV1,
  agentInstructionsSetResponse,
  agentInstructionsSetResponsePayloadV1,
  parseAgentInstructionsGetResponsePayloadV1,
  parseAgentInstructionsSetRequestPayloadV1,
  parseAgentInstructionsSetResponsePayloadV1,
  safeParseAgentInstructionsGetResponsePayloadV1,
  safeParseAgentInstructionsSetRequestPayloadV1,
  safeParseAgentInstructionsSetResponsePayloadV1,
} from './agent-instructions';

export type {
  FsEntryKindV1,
  FsEntryV1,
  FsListErrorV1,
  FsListRequest,
  FsListRequestPayloadV1,
  FsListResponse,
  FsListResponsePayloadV1,
  FsListResultV1,
  FsReadErrorV1,
  FsReadRequest,
  FsReadRequestPayloadV1,
  FsReadResponse,
  FsReadResponsePayloadV1,
  FsReadResultV1,
  FsWriteConflictV1,
  FsWriteErrorV1,
  FsWriteRequest,
  FsWriteRequestPayloadV1,
  FsWriteResponse,
  FsWriteResponsePayloadV1,
  FsWriteResultV1,
} from './fs';
export {
  fsEntryKindV1,
  fsEntryV1,
  fsListErrorV1,
  fsListRequest,
  fsListRequestPayloadV1,
  fsListResponse,
  fsListResponsePayloadV1,
  fsListResultV1,
  fsReadErrorV1,
  fsReadRequest,
  fsReadRequestPayloadV1,
  fsReadResponse,
  fsReadResponsePayloadV1,
  fsReadResultV1,
  fsWriteConflictV1,
  fsWriteErrorV1,
  fsWriteRequest,
  fsWriteRequestPayloadV1,
  fsWriteResponse,
  fsWriteResponsePayloadV1,
  fsWriteResultV1,
  parseFsListRequestPayloadV1,
  parseFsListResponsePayloadV1,
  parseFsReadRequestPayloadV1,
  parseFsReadResponsePayloadV1,
  parseFsWriteRequestPayloadV1,
  parseFsWriteResponsePayloadV1,
  safeParseFsListRequestPayloadV1,
  safeParseFsListResponsePayloadV1,
  safeParseFsReadRequestPayloadV1,
  safeParseFsReadResponsePayloadV1,
  safeParseFsWriteRequestPayloadV1,
  safeParseFsWriteResponsePayloadV1,
} from './fs';

export type {
  GitDiffExplainHunkSideV1,
  GitDiffExplainRequest,
  GitDiffExplainRequestPayloadV1,
  GitDiffExplainResponse,
  GitDiffExplainResponsePayloadV1,
  GitDiffExplainScopeV1,
} from './git-diff-explain';
export {
  gitDiffExplainHunkSideV1,
  gitDiffExplainRequest,
  gitDiffExplainRequestPayloadV1,
  gitDiffExplainResponse,
  gitDiffExplainResponsePayloadV1,
  gitDiffExplainScopeV1,
  parseGitDiffExplainRequestPayloadV1,
  parseGitDiffExplainResponsePayloadV1,
  safeParseGitDiffExplainRequestPayloadV1,
  safeParseGitDiffExplainResponsePayloadV1,
} from './git-diff-explain';

export type {
  GitDiffFileStatusV1,
  GitDiffFileV1,
  GitDiffRequest,
  GitDiffResponse,
  GitDiffResponsePayloadV1,
} from './git-diff';
export {
  gitDiffFileStatusV1,
  gitDiffFileV1,
  gitDiffRequest,
  gitDiffResponse,
  gitDiffResponsePayloadV1,
  parseGitDiffResponsePayloadV1,
  safeParseGitDiffResponsePayloadV1,
} from './git-diff';

export type {
  GitGraphCommitV1,
  GitGraphRefKindV1,
  GitGraphRefV1,
  GitGraphRequest,
  GitGraphRequestPayloadV1,
  GitGraphResponse,
  GitGraphResponsePayloadV1,
} from './git-graph';
export {
  GIT_GRAPH_DEFAULT_LIMIT,
  GIT_GRAPH_MAX_LIMIT,
  gitGraphCommitV1,
  gitGraphRefKindV1,
  gitGraphRefV1,
  gitGraphRequest,
  gitGraphRequestPayloadV1,
  gitGraphResponse,
  gitGraphResponsePayloadV1,
  parseGitGraphRequestPayloadV1,
  parseGitGraphResponsePayloadV1,
  safeParseGitGraphRequestPayloadV1,
  safeParseGitGraphResponsePayloadV1,
} from './git-graph';

export type {
  GitHunkActionRequest,
  GitHunkActionRequestPayloadV1,
  GitHunkActionResponse,
  GitHunkActionResponsePayloadV1,
  GitHunkActionV1,
  GitHunkDiffRequest,
  GitHunkDiffResponse,
  GitHunkDiffResponsePayloadV1,
  GitHunkFileV1,
  GitHunkLineKindV1,
  GitHunkLineV1,
  GitHunkV1,
} from './git-hunks';

export type {
  GitBranchCreateRequest,
  GitBranchCreateRequestPayloadV1,
  GitBranchCreateResponse,
  GitBranchCreateResponsePayloadV1,
  GitBranchListRequest,
  GitBranchListResponse,
  GitBranchListResponsePayloadV1,
  GitBranchMergeAbortRequest,
  GitBranchMergeAbortResponse,
  GitBranchMergeAbortResponsePayloadV1,
  GitBranchMergeRequest,
  GitBranchMergeRequestPayloadV1,
  GitBranchMergeResponse,
  GitBranchMergeResponsePayloadV1,
  GitBranchSummaryV1,
  GitBranchSwitchRequest,
  GitBranchSwitchRequestPayloadV1,
  GitBranchSwitchResponse,
  GitBranchSwitchResponsePayloadV1,
} from './git-branch';
export {
  gitBranchCreateRequest,
  gitBranchCreateRequestPayloadV1,
  gitBranchCreateResponse,
  gitBranchCreateResponsePayloadV1,
  gitBranchListRequest,
  gitBranchListResponse,
  gitBranchListResponsePayloadV1,
  gitBranchMergeAbortRequest,
  gitBranchMergeAbortResponse,
  gitBranchMergeAbortResponsePayloadV1,
  gitBranchMergeRequest,
  gitBranchMergeRequestPayloadV1,
  gitBranchMergeResponse,
  gitBranchMergeResponsePayloadV1,
  gitBranchSummaryV1,
  gitBranchSwitchRequest,
  gitBranchSwitchRequestPayloadV1,
  gitBranchSwitchResponse,
  gitBranchSwitchResponsePayloadV1,
  parseGitBranchCreateRequestPayloadV1,
  parseGitBranchCreateResponsePayloadV1,
  parseGitBranchListResponsePayloadV1,
  parseGitBranchMergeAbortResponsePayloadV1,
  parseGitBranchMergeRequestPayloadV1,
  parseGitBranchMergeResponsePayloadV1,
  parseGitBranchSwitchRequestPayloadV1,
  parseGitBranchSwitchResponsePayloadV1,
  safeParseGitBranchCreateRequestPayloadV1,
  safeParseGitBranchCreateResponsePayloadV1,
  safeParseGitBranchListResponsePayloadV1,
  safeParseGitBranchMergeAbortResponsePayloadV1,
  safeParseGitBranchMergeRequestPayloadV1,
  safeParseGitBranchMergeResponsePayloadV1,
  safeParseGitBranchSwitchRequestPayloadV1,
  safeParseGitBranchSwitchResponsePayloadV1,
} from './git-branch';

export type {
  GitPushRequest,
  GitPushRequestPayloadV1,
  GitPushResponse,
  GitPushResponsePayloadV1,
} from './git-push';
export {
  gitPushRequest,
  gitPushRequestPayloadV1,
  gitPushResponse,
  gitPushResponsePayloadV1,
  parseGitPushRequestPayloadV1,
  parseGitPushResponsePayloadV1,
  safeParseGitPushRequestPayloadV1,
  safeParseGitPushResponsePayloadV1,
} from './git-push';

export type {
  GitStashDropRequest,
  GitStashDropRequestPayloadV1,
  GitStashDropResponse,
  GitStashDropResponsePayloadV1,
  GitStashListRequest,
  GitStashListResponse,
  GitStashListResponsePayloadV1,
  GitStashPopRequest,
  GitStashPopRequestPayloadV1,
  GitStashPopResponse,
  GitStashPopResponsePayloadV1,
  GitStashSaveRequest,
  GitStashSaveRequestPayloadV1,
  GitStashSaveResponse,
  GitStashSaveResponsePayloadV1,
  GitStashSummaryV1,
} from './git-stash';
export {
  gitStashDropRequest,
  gitStashDropRequestPayloadV1,
  gitStashDropResponse,
  gitStashDropResponsePayloadV1,
  gitStashListRequest,
  gitStashListResponse,
  gitStashListResponsePayloadV1,
  gitStashPopRequest,
  gitStashPopRequestPayloadV1,
  gitStashPopResponse,
  gitStashPopResponsePayloadV1,
  gitStashSaveRequest,
  gitStashSaveRequestPayloadV1,
  gitStashSaveResponse,
  gitStashSaveResponsePayloadV1,
  gitStashSummaryV1,
  parseGitStashDropRequestPayloadV1,
  parseGitStashDropResponsePayloadV1,
  parseGitStashListResponsePayloadV1,
  parseGitStashPopRequestPayloadV1,
  parseGitStashPopResponsePayloadV1,
  parseGitStashSaveRequestPayloadV1,
  parseGitStashSaveResponsePayloadV1,
  safeParseGitStashDropRequestPayloadV1,
  safeParseGitStashDropResponsePayloadV1,
  safeParseGitStashListResponsePayloadV1,
  safeParseGitStashPopRequestPayloadV1,
  safeParseGitStashPopResponsePayloadV1,
  safeParseGitStashSaveRequestPayloadV1,
  safeParseGitStashSaveResponsePayloadV1,
} from './git-stash';
export {
  gitHunkActionRequest,
  gitHunkActionRequestPayloadV1,
  gitHunkActionResponse,
  gitHunkActionResponsePayloadV1,
  gitHunkActionV1,
  gitHunkDiffRequest,
  gitHunkDiffResponse,
  gitHunkDiffResponsePayloadV1,
  gitHunkFileV1,
  gitHunkLineKindV1,
  gitHunkLineV1,
  gitHunkV1,
  parseGitHunkActionRequestPayloadV1,
  parseGitHunkActionResponsePayloadV1,
  parseGitHunkDiffResponsePayloadV1,
  safeParseGitHunkActionRequestPayloadV1,
  safeParseGitHunkActionResponsePayloadV1,
  safeParseGitHunkDiffResponsePayloadV1,
} from './git-hunks';

export type {
  GitCommitDraftRequest,
  GitCommitDraftResponse,
  GitCommitDraftResponsePayloadV1,
  GitCommitRequest,
  GitCommitRequestPayloadV1,
  GitCommitResponse,
  GitCommitResponsePayloadV1,
} from './git-commit';
export {
  gitCommitDraftRequest,
  gitCommitDraftResponse,
  gitCommitRequest,
  gitCommitRequestPayloadV1,
  gitCommitResponse,
  parseGitCommitDraftResponsePayloadV1,
  parseGitCommitRequestPayloadV1,
  parseGitCommitResponsePayloadV1,
  safeParseGitCommitDraftResponsePayloadV1,
  safeParseGitCommitRequestPayloadV1,
  safeParseGitCommitResponsePayloadV1,
} from './git-commit';

export type {
  McpPromptGetErrorV1,
  McpPromptGetRequest,
  McpPromptGetRequestPayloadV1,
  McpPromptGetResponse,
  McpPromptGetResponsePayloadV1,
  McpPromptGetResultV1,
} from './mcp-prompts';
export {
  mcpPromptGetErrorV1,
  mcpPromptGetRequest,
  mcpPromptGetRequestPayloadV1,
  mcpPromptGetResponse,
  mcpPromptGetResponsePayloadV1,
  mcpPromptGetResultV1,
  parseMcpPromptGetRequestPayloadV1,
  parseMcpPromptGetResponsePayloadV1,
  safeParseMcpPromptGetRequestPayloadV1,
  safeParseMcpPromptGetResponsePayloadV1,
} from './mcp-prompts';

export type {
  TargetFsListErrorV1,
  TargetFsListRequest,
  TargetFsListRequestPayloadV1,
  TargetFsListResponse,
  TargetFsListResponsePayloadV1,
  TargetFsListResultV1,
} from './target-fs';
export {
  parseTargetFsListRequestPayloadV1,
  parseTargetFsListResponsePayloadV1,
  safeParseTargetFsListRequestPayloadV1,
  safeParseTargetFsListResponsePayloadV1,
  targetFsListErrorV1,
  targetFsListRequest,
  targetFsListRequestPayloadV1,
  targetFsListResponse,
  targetFsListResponsePayloadV1,
  targetFsListResultV1,
} from './target-fs';

export type {
  CustomAgentProbeRequest,
  CustomAgentProbeRequestPayloadV1,
  CustomAgentProbeResponse,
  CustomAgentProbeResponsePayloadV1,
  CustomAgentProbeResultV1,
  CustomAgentRecordV1,
} from './custom-agent';
export {
  customAgentProbeRequest,
  customAgentProbeRequestPayloadV1,
  customAgentProbeResponse,
  customAgentProbeResponsePayloadV1,
  customAgentProbeResultV1,
  customAgentRecordV1,
  parseCustomAgentProbeRequestPayloadV1,
  parseCustomAgentProbeResponsePayloadV1,
  safeParseCustomAgentProbeRequestPayloadV1,
  safeParseCustomAgentProbeResponsePayloadV1,
} from './custom-agent';

export type {
  TerminalClose,
  TerminalClosed,
  TerminalClosedPayloadV1,
  TerminalClosedReasonV1,
  TerminalData,
  TerminalDataPayloadV1,
  TerminalInput,
  TerminalOpen,
  TerminalOpened,
  TerminalOpenErrorV1,
  TerminalOpenOkV1,
  TerminalOpenPayloadV1,
  TerminalOpenResultPayloadV1,
  TerminalOutput,
  TerminalResize,
  TerminalResizePayloadV1,
  TerminalResyncMarker,
} from './terminal';
export {
  parseTerminalClosedPayloadV1,
  parseTerminalDataPayloadV1,
  parseTerminalOpenPayloadV1,
  parseTerminalOpenResultPayloadV1,
  parseTerminalResizePayloadV1,
  safeParseTerminalClosedPayloadV1,
  safeParseTerminalDataPayloadV1,
  safeParseTerminalOpenPayloadV1,
  safeParseTerminalOpenResultPayloadV1,
  safeParseTerminalResizePayloadV1,
  terminalClose,
  terminalClosed,
  terminalClosedPayloadV1,
  terminalClosedReasonV1,
  terminalData,
  terminalDataPayloadV1,
  terminalInput,
  terminalOpen,
  terminalOpened,
  terminalOpenErrorV1,
  terminalOpenOkV1,
  terminalOpenPayloadV1,
  terminalOpenResultPayloadV1,
  terminalOutput,
  terminalResize,
  terminalResizePayloadV1,
  terminalResyncMarker,
} from './terminal';

export type { Presence, ResyncMarker, ResyncRequest } from './presence';
export { presence, resyncMarker, resyncRequest } from './presence';

export type { Ping, Pong } from './heartbeat';
export { HEARTBEAT_CAPABILITY, ping, pong } from './heartbeat';

export type {
  LeaseDenial,
  LeaseGrant,
  LeaseOutcome,
  LeaseRelease,
  LeaseReleaseResult,
  LeaseRequest,
  LeaseRequestAction,
  LeaseResult,
} from './lease';
export {
  leaseDenial,
  leaseGrant,
  leaseOutcome,
  leaseRelease,
  leaseReleaseResult,
  leaseRequest,
  leaseRequestAction,
  leaseResult,
} from './lease';

export type { WireMessageV1 } from './message';
export { parseWireMessageV1, safeParseWireMessageV1, wireMessageV1 } from './message';

export type { AttentionHint, AttentionHintClass } from './attention';
export { attentionHint, attentionHintClass } from './attention';

export type {
  ProvisionProgress,
  ProvisionStepIdV1,
  ProvisionStepStatusV1,
  ProvisionTargetHostInputV1,
  ProvisionTargetRequest,
  ProvisionTargetResult,
} from './provisioning';
export {
  provisionProgress,
  provisionStepIdV1,
  provisionStepStatusV1,
  provisionTargetHostInputV1,
  provisionTargetRequest,
  provisionTargetResult,
} from './provisioning';

export type {
  SshAgentIdentityV1,
  SshAgentInfoV1,
  SshDiscoveryRequest,
  SshDiscoveryResponse,
  SshDiscoveryResultErrorV1,
  SshDiscoveryResultOkV1,
  SshDiscoveryResultV1,
  SshHostCandidateV1,
} from './ssh-discovery';
export {
  sshAgentIdentityV1,
  sshAgentInfoV1,
  sshDiscoveryRequest,
  sshDiscoveryResponse,
  sshDiscoveryResultErrorV1,
  sshDiscoveryResultOkV1,
  sshDiscoveryResultV1,
  sshHostCandidateV1,
} from './ssh-discovery';

export type {
  DecommissionResultV1,
  DecommissionTargetRequest,
  DecommissionTargetResponse,
  TargetUpdateRequest,
  TargetUpdateResponse,
  TargetVersionStatusV1,
} from './target-lifecycle';
export {
  decommissionResultV1,
  decommissionTargetRequest,
  decommissionTargetResponse,
  targetUpdateRequest,
  targetUpdateResponse,
  targetVersionStatusV1,
} from './target-lifecycle';

export type {
  NodeSelfUpdateApplyRequest,
  NodeSelfUpdateApplyResponse,
  NodeSelfUpdateStatusAnnounce,
  NodeSelfUpdateStatusV1,
  NodeSelfUpdateSummaryV1,
} from './node-self-update';
export {
  nodeSelfUpdateApplyRequest,
  nodeSelfUpdateApplyResponse,
  nodeSelfUpdateStatusAnnounce,
  nodeSelfUpdateStatusV1,
  nodeSelfUpdateSummaryV1,
} from './node-self-update';

export type {
  GitHubTarget,
  JiraTarget,
  TrackerBackendResolutionErrorV1,
  TrackerMode,
  TrackerModeGetRequest,
  TrackerModeResponse,
  TrackerModeSetRequest,
} from './tracker';
export {
  githubTarget,
  jiraTarget,
  parseTrackerMode,
  safeParseTrackerMode,
  trackerBackendResolutionErrorV1,
  trackerMode,
  trackerModeGetRequest,
  trackerModeResponse,
  trackerModeSetRequest,
} from './tracker';
export type {
  ConnectedAccount,
  ConnectedAccountAnnounce,
  ConnectedAccountCredentialSource,
  ConnectedAccountIdParts,
  ConnectedAccountList,
  ConnectedAccountListRequest,
} from './connected-accounts';
export {
  composeConnectedAccountId,
  connectedAccount,
  connectedAccountAnnounce,
  connectedAccountCredentialSource,
  connectedAccountList,
  connectedAccountListRequest,
  connectedAccountSecretRef,
  parseConnectedAccountId,
} from './connected-accounts';

export type {
  TestRunnerCommandsV1,
  TestRunnerConfigDetect,
  TestRunnerConfigDetectedPayloadV1,
  TestRunnerConfigDetected,
  TestRunnerConfigGet,
  TestRunnerConfigResultPayloadV1,
  TestRunnerConfigResult,
  TestRunnerConfigSetPayloadV1,
  TestRunnerConfigSet,
} from './test-runner-config';
export {
  parseTestRunnerConfigDetectedPayloadV1,
  parseTestRunnerConfigResultPayloadV1,
  parseTestRunnerConfigSetPayloadV1,
  safeParseTestRunnerConfigDetectedPayloadV1,
  safeParseTestRunnerConfigResultPayloadV1,
  safeParseTestRunnerConfigSetPayloadV1,
  testRunnerCommandsV1,
  testRunnerConfigDetect,
  testRunnerConfigDetected,
  testRunnerConfigGet,
  testRunnerConfigResult,
  testRunnerConfigSet,
} from './test-runner-config';
export type {
  PermissionRuleSetV1,
  PermissionPolicyV1,
  PermissionPolicyResultPayloadV1,
  PermissionPolicySetPayloadV1,
  PermissionPolicyGet,
  PermissionPolicySet,
  PermissionPolicyResult,
  ToolRefusalReasonV1,
  PermissionPolicyViolationPayloadV1,
  PermissionPolicyViolation,
} from './permission-policy';
export {
  EMPTY_PERMISSION_POLICY_V1,
  parsePermissionPolicyResultPayloadV1,
  parsePermissionPolicySetPayloadV1,
  parsePermissionPolicyViolationPayloadV1,
  safeParsePermissionPolicyResultPayloadV1,
  safeParsePermissionPolicySetPayloadV1,
  safeParsePermissionPolicyViolationPayloadV1,
  permissionPolicyGet,
  permissionPolicySet,
  permissionPolicyResult,
  permissionPolicyViolation,
  permissionPolicyV1,
  permissionRuleSetV1,
  toolRefusalReasonV1,
} from './permission-policy';
export type {
  SpendCapSetPayloadV1,
  SpendCapResultPayloadV1,
  SpendCapGet,
  SpendCapSet,
  SpendCapResult,
  SessionSpendCapResume,
} from './spend-cap';
export {
  parseSpendCapSetPayloadV1,
  safeParseSpendCapSetPayloadV1,
  parseSpendCapResultPayloadV1,
  safeParseSpendCapResultPayloadV1,
  spendCapGet,
  spendCapSet,
  spendCapResult,
  sessionSpendCapResume,
} from './spend-cap';
export type {
  SpendReportRowV1,
  SpendReportResponsePayloadV1,
  SpendReportRequest,
  SpendReportResponse,
} from './spend-report';
export {
  spendReportRowV1,
  spendReportResponsePayloadV1,
  parseSpendReportResponsePayloadV1,
  safeParseSpendReportResponsePayloadV1,
  spendReportRequest,
  spendReportResponse,
} from './spend-report';
export type {
  GitCheckpointV1,
  RestorePreviewV1,
  RestoreResultV1,
  CheckpointErrorTypeV1,
  CheckpointCreate,
  CheckpointCreatePayloadV1,
  CheckpointResult,
  CheckpointResultPayloadV1,
  CheckpointList,
  CheckpointListResult,
  CheckpointListResultPayloadV1,
  CheckpointRestorePreview,
  CheckpointRestorePreviewResult,
  CheckpointRestorePreviewResultPayloadV1,
  CheckpointRestore,
  CheckpointRestoreResult,
  CheckpointRestoreResultPayloadV1,
} from './checkpoint';
export {
  gitCheckpointV1,
  restorePreviewV1,
  restoreResultV1,
  checkpointErrorTypeV1,
  checkpointCreate,
  parseCheckpointCreatePayloadV1,
  safeParseCheckpointCreatePayloadV1,
  checkpointResult,
  parseCheckpointResultPayloadV1,
  safeParseCheckpointResultPayloadV1,
  checkpointList,
  checkpointListResult,
  parseCheckpointListResultPayloadV1,
  safeParseCheckpointListResultPayloadV1,
  checkpointRestorePreview,
  checkpointRestorePreviewResult,
  parseCheckpointRestorePreviewResultPayloadV1,
  safeParseCheckpointRestorePreviewResultPayloadV1,
  checkpointRestore,
  checkpointRestoreResult,
  parseCheckpointRestoreResultPayloadV1,
  safeParseCheckpointRestoreResultPayloadV1,
} from './checkpoint';
export type {
  RewindFileChangeV1,
  RewindErrorTypeV1,
  RewindPreviewV1,
  RewindResultV1,
  SessionRewindPreview,
  SessionRewindPreviewResult,
  SessionRewindPreviewResultPayloadV1,
  SessionRewind,
  SessionRewindResult,
  SessionRewindResultPayloadV1,
} from './rewind';
export {
  rewindFileChangeV1,
  rewindErrorTypeV1,
  rewindPreviewV1,
  rewindResultV1,
  sessionRewindPreview,
  sessionRewindPreviewResult,
  parseSessionRewindPreviewResultPayloadV1,
  safeParseSessionRewindPreviewResultPayloadV1,
  sessionRewind,
  sessionRewindResult,
  parseSessionRewindResultPayloadV1,
  safeParseSessionRewindResultPayloadV1,
} from './rewind';
export type {
  PrOpenFailureCategory,
  PrOpenFailure,
  PrOpenPreviewOutcome,
  PrOpenPreviewResultPayloadV1,
  PrOpenPreviewRequest,
  PrOpenPreviewResult,
  PrOpenRequestPayloadV1,
  PrOpenRequest,
  PrOpenOutcome,
  PrOpenResultPayloadV1,
  PrOpenResult,
} from './pr';
export {
  parsePrOpenPreviewResultPayloadV1,
  parsePrOpenRequestPayloadV1,
  parsePrOpenResultPayloadV1,
  safeParsePrOpenPreviewResultPayloadV1,
  safeParsePrOpenRequestPayloadV1,
  safeParsePrOpenResultPayloadV1,
  prOpenFailureCategory,
  prOpenFailure,
  prOpenPreviewOutcome,
  prOpenPreviewRequest,
  prOpenPreviewResult,
  prOpenRequest,
  prOpenResult,
  prOpenOutcome,
} from './pr';
export type {
  CiCheckRunV1,
  CiCheckOverallStateV1,
  CiCheckStateV1,
  CiCheckStatusPayloadV1,
  CiCheckStatus,
} from './ci-check';
export {
  ciCheckRunV1,
  ciCheckOverallStateV1,
  ciCheckStateV1,
  parseCiCheckStatusPayloadV1,
  safeParseCiCheckStatusPayloadV1,
  ciCheckStatusPayloadV1,
  ciCheckStatus,
} from './ci-check';
export type {
  ReviewCommentThreadV1,
  ReviewCommentOverallStateV1,
  ReviewCommentStateV1,
  ReviewCommentStatusPayloadV1,
  ReviewCommentStatus,
} from './review-comment';
export {
  reviewCommentThreadV1,
  reviewCommentOverallStateV1,
  reviewCommentStateV1,
  parseReviewCommentStatusPayloadV1,
  safeParseReviewCommentStatusPayloadV1,
  reviewCommentStatusPayloadV1,
  reviewCommentStatus,
} from './review-comment';
export type {
  PrMergeMethod,
  PrMergeBlockedReason,
  PrMergeFailureCategory,
  PrMergeOutcome,
  PrMergeRequestPayloadV1,
  PrMergeRequest,
  PrMergeResultPayloadV1,
  PrMergeResult,
} from './pr-merge';
export {
  prMergeMethod,
  prMergeBlockedReason,
  prMergeFailureCategory,
  prMergeOutcome,
  parsePrMergeRequestPayloadV1,
  safeParsePrMergeRequestPayloadV1,
  prMergeRequestPayloadV1,
  prMergeRequest,
  parsePrMergeResultPayloadV1,
  safeParsePrMergeResultPayloadV1,
  prMergeResultPayloadV1,
  prMergeResult,
} from './pr-merge';
export type {
  TrackerConnectivityStateV1,
  TrackerConnectivityStatusPayloadV1,
  TrackerConnectivityStatus,
} from './tracker-connectivity';
export {
  trackerConnectivityStateV1,
  parseTrackerConnectivityStatusPayloadV1,
  safeParseTrackerConnectivityStatusPayloadV1,
  trackerConnectivityStatusPayloadV1,
  trackerConnectivityStatus,
} from './tracker-connectivity';
export type {
  CiAutoIterateStopReasonV1,
  CiAutoIterateAttemptV1,
  CiAutoIterateStateV1,
  CiAutoIterateStatusPayloadV1,
  CiAutoIterateStatus,
  CiAutoIterateStop,
} from './ci-auto-iterate';
export {
  ciAutoIterateStopReasonV1,
  ciAutoIterateAttemptV1,
  ciAutoIterateStateV1,
  parseCiAutoIterateStatusPayloadV1,
  safeParseCiAutoIterateStatusPayloadV1,
  ciAutoIterateStatusPayloadV1,
  ciAutoIterateStatus,
  ciAutoIterateStop,
} from './ci-auto-iterate';
export type {
  RunStatusEntryV1,
  RunStatusOverallStateV1,
  RunStatusStateV1,
  RunStatusPayloadV1,
  RunStatus,
} from './run-status';
export {
  runStatusEntryV1,
  runStatusOverallStateV1,
  runStatusStateV1,
  parseRunStatusPayloadV1,
  safeParseRunStatusPayloadV1,
  runStatusPayloadV1,
  runStatus,
} from './run-status';
export type { KeymapV1, KeymapGetRequest, KeymapSetRequest, KeymapResult } from './keymap';
export { keymapV1, keymapGetRequest, keymapSetRequest, keymapResult } from './keymap';
export type {
  AgentProfileV1,
  AgentProfileListResultPayloadV1,
  AgentProfileListSetPayloadV1,
  AgentProfileListGet,
  AgentProfileListSet,
  AgentProfileListResult,
  AgentProfileSessionPayloadV1,
  AgentProfileSessionGet,
  AgentProfileSessionSet,
  AgentProfileSessionResult,
  AgentProfileSessionErrorPayloadV1,
} from './agent-profile';
export {
  agentProfileV1,
  parseAgentProfileListResultPayloadV1,
  safeParseAgentProfileListResultPayloadV1,
  parseAgentProfileListSetPayloadV1,
  safeParseAgentProfileListSetPayloadV1,
  agentProfileListGet,
  agentProfileListSet,
  agentProfileListResult,
  parseAgentProfileSessionPayloadV1,
  safeParseAgentProfileSessionPayloadV1,
  agentProfileSessionGet,
  agentProfileSessionSet,
  agentProfileSessionResult,
  agentProfileSessionErrorPayloadV1,
} from './agent-profile';
export type {
  SessionTemplateV1,
  SessionTemplateListResultPayloadV1,
  SessionTemplateListSetPayloadV1,
  SessionTemplateListGet,
  SessionTemplateListSet,
  SessionTemplateListResult,
} from './session-template';
export {
  sessionTemplateV1,
  parseSessionTemplateListResultPayloadV1,
  safeParseSessionTemplateListResultPayloadV1,
  parseSessionTemplateListSetPayloadV1,
  safeParseSessionTemplateListSetPayloadV1,
  sessionTemplateListGet,
  sessionTemplateListSet,
  sessionTemplateListResult,
} from './session-template';
export type {
  AccountPinErrorType,
  AccountPinGetRequest,
  AccountPinMapV1,
  AccountPinResolveOutcome,
  AccountPinResolveRequest,
  AccountPinResolveResponse,
  AccountPinResponse,
  AccountPinSetRequest,
  AccountPinUnsetRequest,
  ConnectedAccountDisconnectRequest,
  ConnectedAccountDisconnectResponse,
  GithubConnectCancelRequest,
  GithubConnectDeviceCode,
  GithubConnectOutcome,
  GithubConnectResult,
  GithubConnectStartRequest,
  JiraConnectOutcome,
  JiraConnectRequest,
  JiraConnectResponse,
} from './account-connect';
export {
  accountPinErrorType,
  accountPinGetRequest,
  accountPinMapV1,
  accountPinResolveOutcome,
  accountPinResolveRequest,
  accountPinResolveResponse,
  accountPinResponse,
  accountPinSetRequest,
  accountPinUnsetRequest,
  connectedAccountDisconnectRequest,
  connectedAccountDisconnectResponse,
  githubConnectCancelRequest,
  githubConnectDeviceCode,
  githubConnectOutcome,
  githubConnectResult,
  githubConnectStartRequest,
  jiraConnectOutcome,
  jiraConnectRequest,
  jiraConnectResponse,
} from './account-connect';
export type { WorkflowCategoryV1 } from './tracker-records';
export type {
  TrackerRoleV1,
  TrackerSnapshotErrorV1,
  TrackerSnapshotRequest,
  TrackerSnapshotRequestPayloadV1,
  TrackerSnapshotResponse,
  TrackerSnapshotResponsePayloadV1,
  TrackerSnapshotResultV1,
  TrackerSystemV1,
  TrackerRecordV1,
  TrackerTypeDefinitionV1,
  TrackerTypeRegistryV1,
  TrackerWriteErrorV1,
  TrackerWriteRequest,
  TrackerWriteRequestPayloadV1,
  TrackerWriteResponse,
  TrackerWriteResponsePayloadV1,
  TrackerWriteResultV1,
} from './tracker-records';
export {
  groupByWorkflowCategory,
  resolveWorkflowCategory,
  WORKFLOW_CATEGORIES_V1,
  WORKFLOW_CATEGORY_COLUMNS_V1,
  buildTrackerTypeRegistryV1,
  filterByAssignee,
  groupByWorkflowStatus,
  parseTrackerSnapshotRequestPayloadV1,
  parseTrackerSnapshotResponsePayloadV1,
  parseTrackerWriteRequestPayloadV1,
  parseTrackerWriteResponsePayloadV1,
  resolveRoleValue,
  safeParseTrackerSnapshotRequestPayloadV1,
  safeParseTrackerSnapshotResponsePayloadV1,
  safeParseTrackerWriteRequestPayloadV1,
  safeParseTrackerWriteResponsePayloadV1,
  TRACKER_ROLES,
  sortByPriority,
  trackerRecordV1,
  trackerRoleV1,
  trackerSnapshotRequest,
  trackerSnapshotRequestPayloadV1,
  trackerSnapshotResponse,
  trackerSnapshotResponsePayloadV1,
  trackerSnapshotResultV1,
  trackerSystemV1,
  trackerTypeDefinitionV1,
  trackerWriteRequest,
  trackerWriteRequestPayloadV1,
  trackerWriteResponse,
  trackerWriteResponsePayloadV1,
  trackerWriteResultV1,
  UNRESOLVED_WORKFLOW_STATUS,
} from './tracker-records';

export type {
  RunCancel,
  RunExit,
  RunExitOutcomeV1,
  RunExitPayloadV1,
  RunOutput,
  RunOutputPayloadV1,
  RunStart,
  RunStarted,
  RunStartedErrorV1,
  RunStartedOkV1,
  RunStartedResultPayloadV1,
  RunStartPayloadV1,
  TestRunnerKindV1,
} from './test-runner';
export {
  parseRunExitPayloadV1,
  parseRunOutputPayloadV1,
  parseRunStartedResultPayloadV1,
  parseRunStartPayloadV1,
  runCancel,
  runExit,
  runExitOutcomeV1,
  runExitPayloadV1,
  runOutput,
  runOutputPayloadV1,
  runStart,
  runStarted,
  runStartedErrorV1,
  runStartedOkV1,
  runStartedResultPayloadV1,
  runStartPayloadV1,
  safeParseRunExitPayloadV1,
  safeParseRunOutputPayloadV1,
  safeParseRunStartedResultPayloadV1,
  safeParseRunStartPayloadV1,
  testRunnerKindV1,
} from './test-runner';

import { base64String, encryptedEnvelope, encryptionAlg } from './envelope';
import { baseMessageV1, initialize, initializeResult, wireRole } from './handshake';
import {
  amkEpochFetchRequest,
  amkEpochFetchResponse,
  amkEscrow,
  deviceRegister,
  deviceRevoke,
  deviceRotate,
  newDeviceBootstrapRequest,
  newDeviceBootstrapResponse,
  qrPairingRequest,
  qrPairingResponse,
  wrappedAmkEnvelope,
} from './devices';
import {
  targetAnnounce,
  targetDescriptor,
  targetHealth,
  targetKind,
  targetList,
  targetListEntry,
  targetListRequest,
  targetResourceSample,
  targetStatus,
} from './targets';
import {
  sessionAnnounceV1,
  sessionCreate,
  sessionListRequest,
  sessionListV1,
  sessionMetaPublic,
  sessionResume,
  sessionWithPrivateEnvelope,
} from './sessions';
import {
  mcpHttpServerConfigV1,
  mcpServerConfigV1,
  mcpServerVarDeclV1,
  mcpSseServerConfigV1,
  mcpStdioServerConfigV1,
} from './mcp-servers';
import {
  sessionArchiveRequest,
  sessionArchiveResponse,
  sessionArchiveResult,
  sessionForkRequest,
  sessionForkResponse,
  sessionForkResult,
} from './session-lifecycle';
import { sessionUpdateEnvelopeV1 } from './transcript';
import {
  acpAvailableCommandInputV1,
  acpAvailableCommandV1,
  acpConfigOptionChoiceV1,
  acpConfigOptionV1,
  availableCommandsUpdateEventV1,
  configOptionsEventV1,
  configOptionUpdateEventV1,
  mcpServerFailureCategoryV1,
  mcpServerPromptArgumentV1,
  mcpServerPromptV1,
  mcpServerPromptsEntryV1,
  mcpServerPromptsEventV1,
  mcpServerStatusEntryV1,
  mcpServerStatusEventV1,
  sessionLifecycleEventV1,
  sessionStatusEventV1,
  sessionStatusV1,
  turnEndedEventV1,
  turnStartedEventV1,
} from './session-events';
import {
  configOption,
  configOptionResult,
  permissionDecision,
  permissionRequest,
  permissionResponse,
  promptInjectV1,
} from './steering';
import {
  blobDownload,
  blobDownloadResponse,
  blobRef,
  blobUpload,
  fileEventPayloadV1,
} from './attachments';
import {
  fsEntryKindV1,
  fsEntryV1,
  fsListErrorV1,
  fsListRequest,
  fsListRequestPayloadV1,
  fsListResponse,
  fsListResponsePayloadV1,
  fsListResultV1,
  fsWriteConflictV1,
  fsWriteErrorV1,
  fsWriteRequest,
  fsWriteRequestPayloadV1,
  fsWriteResponse,
  fsWriteResponsePayloadV1,
  fsWriteResultV1,
} from './fs';
import {
  mcpPromptGetErrorV1,
  mcpPromptGetRequest,
  mcpPromptGetRequestPayloadV1,
  mcpPromptGetResponse,
  mcpPromptGetResponsePayloadV1,
  mcpPromptGetResultV1,
} from './mcp-prompts';
import {
  targetFsListErrorV1,
  targetFsListRequest,
  targetFsListRequestPayloadV1,
  targetFsListResponse,
  targetFsListResponsePayloadV1,
  targetFsListResultV1,
} from './target-fs';
import {
  customAgentProbeRequest,
  customAgentProbeRequestPayloadV1,
  customAgentProbeResponse,
  customAgentProbeResponsePayloadV1,
  customAgentProbeResultV1,
  customAgentRecordV1,
} from './custom-agent';
import { presence, resyncMarker, resyncRequest } from './presence';
import {
  leaseDenial,
  leaseGrant,
  leaseOutcome,
  leaseRelease,
  leaseReleaseResult,
  leaseRequest,
  leaseRequestAction,
  leaseResult,
} from './lease';
import {
  terminalClose,
  terminalClosed,
  terminalClosedPayloadV1,
  terminalData,
  terminalDataPayloadV1,
  terminalInput,
  terminalOpen,
  terminalOpened,
  terminalOpenResultPayloadV1,
  terminalOpenPayloadV1,
  terminalOutput,
  terminalResize,
  terminalResizePayloadV1,
} from './terminal';
import { wireMessageV1 } from './message';
import { attentionHint, attentionHintClass } from './attention';
import {
  provisionProgress,
  provisionStepIdV1,
  provisionStepStatusV1,
  provisionTargetHostInputV1,
  provisionTargetRequest,
  provisionTargetResult,
} from './provisioning';
import {
  sshAgentIdentityV1,
  sshAgentInfoV1,
  sshDiscoveryRequest,
  sshDiscoveryResponse,
  sshDiscoveryResultErrorV1,
  sshDiscoveryResultOkV1,
  sshDiscoveryResultV1,
  sshHostCandidateV1,
} from './ssh-discovery';
import {
  decommissionResultV1,
  decommissionTargetRequest,
  decommissionTargetResponse,
  targetUpdateRequest,
  targetUpdateResponse,
  targetVersionStatusV1,
} from './target-lifecycle';
import {
  nodeSelfUpdateApplyRequest,
  nodeSelfUpdateApplyResponse,
  nodeSelfUpdateStatusAnnounce,
  nodeSelfUpdateStatusV1,
  nodeSelfUpdateSummaryV1,
} from './node-self-update';
import {
  githubTarget,
  jiraTarget,
  trackerMode,
  trackerModeGetRequest,
  trackerModeResponse,
  trackerModeSetRequest,
} from './tracker';
import {
  connectedAccount,
  connectedAccountAnnounce,
  connectedAccountCredentialSource,
  connectedAccountList,
  connectedAccountListRequest,
} from './connected-accounts';
import {
  testRunnerCommandsV1,
  testRunnerConfigDetect,
  testRunnerConfigDetected,
  testRunnerConfigGet,
  testRunnerConfigResult,
  testRunnerConfigSet,
} from './test-runner-config';
import {
  prOpenFailureCategory,
  prOpenFailure,
  prOpenPreviewOutcome,
  prOpenPreviewRequest,
  prOpenPreviewResult,
  prOpenRequest,
  prOpenResult,
  prOpenOutcome,
} from './pr';
import {
  ciCheckRunV1,
  ciCheckOverallStateV1,
  ciCheckStateV1,
  ciCheckStatusPayloadV1,
  ciCheckStatus,
} from './ci-check';
import {
  reviewCommentThreadV1,
  reviewCommentOverallStateV1,
  reviewCommentStateV1,
  reviewCommentStatusPayloadV1,
  reviewCommentStatus,
} from './review-comment';
import {
  prMergeMethod,
  prMergeBlockedReason,
  prMergeFailureCategory,
  prMergeOutcome,
  prMergeRequestPayloadV1,
  prMergeRequest,
  prMergeResultPayloadV1,
  prMergeResult,
} from './pr-merge';
import {
  trackerConnectivityStateV1,
  trackerConnectivityStatusPayloadV1,
  trackerConnectivityStatus,
} from './tracker-connectivity';
import {
  ciAutoIterateStopReasonV1,
  ciAutoIterateAttemptV1,
  ciAutoIterateStateV1,
  ciAutoIterateStatusPayloadV1,
  ciAutoIterateStatus,
  ciAutoIterateStop,
} from './ci-auto-iterate';
import {
  gitGraphCommitV1,
  gitGraphRefKindV1,
  gitGraphRefV1,
  gitGraphRequest,
  gitGraphRequestPayloadV1,
  gitGraphResponse,
  gitGraphResponsePayloadV1,
} from './git-graph';
import {
  runStatusEntryV1,
  runStatusOverallStateV1,
  runStatusStateV1,
  runStatusPayloadV1,
  runStatus,
} from './run-status';
import {
  permissionPolicyGet,
  permissionPolicyResult,
  permissionPolicySet,
  permissionPolicyV1,
  permissionPolicyViolation,
  permissionRuleSetV1,
  toolRefusalReasonV1,
} from './permission-policy';
import {
  checkpointCreate,
  checkpointList,
  checkpointListResult,
  checkpointResult,
  checkpointRestore,
  checkpointRestorePreview,
  checkpointRestorePreviewResult,
  checkpointRestoreResult,
  gitCheckpointV1,
  restorePreviewV1,
  restoreResultV1,
  checkpointErrorTypeV1,
} from './checkpoint';
import { keymapGetRequest, keymapResult, keymapSetRequest, keymapV1 } from './keymap';
import {
  agentProfileV1,
  agentProfileListGet,
  agentProfileListSet,
  agentProfileListResult,
  agentProfileSessionGet,
  agentProfileSessionSet,
  agentProfileSessionResult,
  agentProfileSessionErrorPayloadV1,
} from './agent-profile';
import {
  sessionTemplateV1,
  sessionTemplateListGet,
  sessionTemplateListSet,
  sessionTemplateListResult,
} from './session-template';
import {
  spendCapSetPayloadV1,
  spendCapResultPayloadV1,
  spendCapGet,
  spendCapSet,
  spendCapResult,
  sessionSpendCapResume,
} from './spend-cap';
import {
  spendReportRowV1,
  spendReportResponsePayloadV1,
  spendReportRequest,
  spendReportResponse,
} from './spend-report';
import {
  accountPinErrorType,
  accountPinGetRequest,
  accountPinMapV1,
  accountPinResolveOutcome,
  accountPinResolveRequest,
  accountPinResolveResponse,
  accountPinResponse,
  accountPinSetRequest,
  accountPinUnsetRequest,
  connectedAccountDisconnectRequest,
  connectedAccountDisconnectResponse,
  githubConnectCancelRequest,
  githubConnectDeviceCode,
  githubConnectOutcome,
  githubConnectResult,
  githubConnectStartRequest,
  jiraConnectOutcome,
  jiraConnectRequest,
  jiraConnectResponse,
} from './account-connect';
import {
  trackerRecordV1,
  trackerSnapshotErrorV1,
  trackerSnapshotRequest,
  trackerSnapshotRequestPayloadV1,
  trackerSnapshotResponse,
  trackerSnapshotResponsePayloadV1,
  trackerSnapshotResultV1,
  trackerSystemV1,
  trackerTypeDefinitionV1,
  trackerRoleV1,
  trackerWriteErrorV1,
  trackerWriteRequest,
  trackerWriteRequestPayloadV1,
  trackerWriteResponse,
  trackerWriteResponsePayloadV1,
  trackerWriteResultV1,
} from './tracker-records';
import {
  runCancel,
  runExit,
  runExitOutcomeV1,
  runExitPayloadV1,
  runOutput,
  runOutputPayloadV1,
  runStart,
  runStarted,
  runStartedResultPayloadV1,
  runStartPayloadV1,
  testRunnerKindV1,
} from './test-runner';
import {
  agentInstructionsFileNameV1,
  agentInstructionsFileStateV1,
  agentInstructionsGetRequest,
  agentInstructionsGetResponse,
  agentInstructionsGetResponsePayloadV1,
  agentInstructionsSetRequest,
  agentInstructionsSetRequestPayloadV1,
  agentInstructionsSetResponse,
  agentInstructionsSetResponsePayloadV1,
} from './agent-instructions';

/** Registry of every v1 wire schema, for introspection/tooling (mirrors v0's `schemas` in `../index.ts`). */
export const schemasV1 = {
  base64String,
  encryptedEnvelope,
  encryptionAlg,
  baseMessageV1,
  wireRole,
  initialize,
  initializeResult,
  deviceRegister,
  wrappedAmkEnvelope,
  deviceRevoke,
  deviceRotate,
  amkEscrow,
  amkEpochFetchRequest,
  amkEpochFetchResponse,
  newDeviceBootstrapRequest,
  newDeviceBootstrapResponse,
  qrPairingRequest,
  qrPairingResponse,
  targetKind,
  targetDescriptor,
  targetAnnounce,
  targetHealth,
  targetResourceSample,
  targetStatus,
  targetListEntry,
  targetListRequest,
  targetList,
  sessionMetaPublic,
  sessionWithPrivateEnvelope,
  sessionCreate,
  sessionAnnounceV1,
  sessionResume,
  sessionListRequest,
  sessionListV1,
  sessionArchiveRequest,
  sessionArchiveResponse,
  sessionArchiveResult,
  mcpServerVarDeclV1,
  mcpStdioServerConfigV1,
  mcpHttpServerConfigV1,
  mcpSseServerConfigV1,
  mcpServerConfigV1,
  sessionForkRequest,
  sessionForkResponse,
  sessionForkResult,
  sessionUpdateEnvelopeV1,
  acpConfigOptionChoiceV1,
  acpConfigOptionV1,
  acpAvailableCommandInputV1,
  acpAvailableCommandV1,
  availableCommandsUpdateEventV1,
  sessionStatusV1,
  sessionStatusEventV1,
  configOptionsEventV1,
  configOptionUpdateEventV1,
  turnStartedEventV1,
  turnEndedEventV1,
  sessionLifecycleEventV1,
  mcpServerFailureCategoryV1,
  mcpServerStatusEntryV1,
  mcpServerStatusEventV1,
  mcpServerPromptArgumentV1,
  mcpServerPromptV1,
  mcpServerPromptsEntryV1,
  mcpServerPromptsEventV1,
  promptInjectV1,
  permissionDecision,
  permissionRequest,
  permissionResponse,
  configOption,
  configOptionResult,
  blobUpload,
  blobRef,
  fileEventPayloadV1,
  blobDownload,
  blobDownloadResponse,
  fsEntryKindV1,
  fsEntryV1,
  fsListRequestPayloadV1,
  fsListResultV1,
  fsListErrorV1,
  fsListResponsePayloadV1,
  fsListRequest,
  fsListResponse,
  fsWriteRequestPayloadV1,
  fsWriteResultV1,
  fsWriteConflictV1,
  fsWriteErrorV1,
  fsWriteResponsePayloadV1,
  fsWriteRequest,
  fsWriteResponse,
  mcpPromptGetRequestPayloadV1,
  mcpPromptGetResultV1,
  mcpPromptGetErrorV1,
  mcpPromptGetResponsePayloadV1,
  mcpPromptGetRequest,
  mcpPromptGetResponse,
  targetFsListRequestPayloadV1,
  targetFsListResultV1,
  targetFsListErrorV1,
  targetFsListResponsePayloadV1,
  targetFsListRequest,
  targetFsListResponse,
  customAgentRecordV1,
  customAgentProbeRequestPayloadV1,
  customAgentProbeResultV1,
  customAgentProbeResponsePayloadV1,
  customAgentProbeRequest,
  customAgentProbeResponse,
  terminalOpenPayloadV1,
  terminalOpenResultPayloadV1,
  terminalDataPayloadV1,
  terminalResizePayloadV1,
  terminalClosedPayloadV1,
  terminalOpen,
  terminalOpened,
  terminalInput,
  terminalOutput,
  terminalData,
  terminalResize,
  terminalClose,
  terminalClosed,
  presence,
  resyncRequest,
  resyncMarker,
  leaseRequestAction,
  leaseRequest,
  leaseGrant,
  leaseDenial,
  leaseOutcome,
  leaseResult,
  leaseRelease,
  leaseReleaseResult,
  wireMessageV1,
  attentionHintClass,
  attentionHint,
  provisionTargetHostInputV1,
  provisionStepIdV1,
  provisionStepStatusV1,
  provisionTargetRequest,
  provisionProgress,
  provisionTargetResult,
  sshAgentIdentityV1,
  sshAgentInfoV1,
  sshHostCandidateV1,
  sshDiscoveryResultOkV1,
  sshDiscoveryResultErrorV1,
  sshDiscoveryResultV1,
  sshDiscoveryRequest,
  sshDiscoveryResponse,
  decommissionResultV1,
  decommissionTargetRequest,
  decommissionTargetResponse,
  targetVersionStatusV1,
  targetUpdateRequest,
  targetUpdateResponse,
  nodeSelfUpdateStatusV1,
  nodeSelfUpdateSummaryV1,
  nodeSelfUpdateStatusAnnounce,
  nodeSelfUpdateApplyRequest,
  nodeSelfUpdateApplyResponse,
  githubTarget,
  jiraTarget,
  trackerMode,
  connectedAccountCredentialSource,
  connectedAccount,
  connectedAccountAnnounce,
  connectedAccountListRequest,
  connectedAccountList,
  testRunnerCommandsV1,
  testRunnerConfigGet,
  testRunnerConfigSet,
  testRunnerConfigResult,
  testRunnerConfigDetect,
  testRunnerConfigDetected,
  permissionRuleSetV1,
  permissionPolicyV1,
  permissionPolicyGet,
  permissionPolicySet,
  permissionPolicyResult,
  toolRefusalReasonV1,
  permissionPolicyViolation,
  checkpointCreate,
  checkpointResult,
  checkpointList,
  checkpointListResult,
  checkpointRestorePreview,
  checkpointRestorePreviewResult,
  checkpointRestore,
  checkpointRestoreResult,
  gitCheckpointV1,
  restorePreviewV1,
  restoreResultV1,
  checkpointErrorTypeV1,
  agentProfileV1,
  agentProfileListGet,
  agentProfileListSet,
  agentProfileListResult,
  agentProfileSessionGet,
  agentProfileSessionSet,
  agentProfileSessionResult,
  agentProfileSessionErrorPayloadV1,
  sessionTemplateV1,
  sessionTemplateListGet,
  sessionTemplateListSet,
  sessionTemplateListResult,
  spendCapSetPayloadV1,
  spendCapResultPayloadV1,
  spendCapGet,
  spendCapSet,
  spendCapResult,
  sessionSpendCapResume,
  spendReportRowV1,
  spendReportResponsePayloadV1,
  spendReportRequest,
  spendReportResponse,
  githubConnectStartRequest,
  githubConnectCancelRequest,
  githubConnectDeviceCode,
  githubConnectOutcome,
  githubConnectResult,
  jiraConnectRequest,
  jiraConnectOutcome,
  jiraConnectResponse,
  connectedAccountDisconnectRequest,
  connectedAccountDisconnectResponse,
  accountPinMapV1,
  accountPinGetRequest,
  accountPinSetRequest,
  accountPinUnsetRequest,
  accountPinResponse,
  accountPinErrorType,
  accountPinResolveRequest,
  accountPinResolveOutcome,
  accountPinResolveResponse,
  trackerRoleV1,
  trackerTypeDefinitionV1,
  trackerSystemV1,
  trackerRecordV1,
  trackerSnapshotRequestPayloadV1,
  trackerSnapshotResultV1,
  trackerSnapshotErrorV1,
  trackerSnapshotResponsePayloadV1,
  trackerModeGetRequest,
  trackerModeSetRequest,
  trackerModeResponse,
  trackerSnapshotRequest,
  trackerSnapshotResponse,
  trackerWriteRequestPayloadV1,
  trackerWriteResultV1,
  trackerWriteErrorV1,
  trackerWriteResponsePayloadV1,
  trackerWriteRequest,
  trackerWriteResponse,
  testRunnerKindV1,
  runStartPayloadV1,
  runStartedResultPayloadV1,
  runOutputPayloadV1,
  runExitOutcomeV1,
  runExitPayloadV1,
  runStart,
  runStarted,
  runOutput,
  runExit,
  runCancel,
  keymapV1,
  keymapGetRequest,
  keymapSetRequest,
  keymapResult,
  prOpenFailureCategory,
  prOpenFailure,
  prOpenPreviewOutcome,
  prOpenPreviewRequest,
  prOpenPreviewResult,
  prOpenRequest,
  prOpenResult,
  prOpenOutcome,
  ciCheckRunV1,
  ciCheckOverallStateV1,
  ciCheckStateV1,
  ciCheckStatusPayloadV1,
  ciCheckStatus,
  reviewCommentThreadV1,
  reviewCommentOverallStateV1,
  reviewCommentStateV1,
  reviewCommentStatusPayloadV1,
  reviewCommentStatus,
  prMergeMethod,
  prMergeBlockedReason,
  prMergeFailureCategory,
  prMergeOutcome,
  prMergeRequestPayloadV1,
  prMergeRequest,
  prMergeResultPayloadV1,
  prMergeResult,
  trackerConnectivityStateV1,
  trackerConnectivityStatusPayloadV1,
  trackerConnectivityStatus,
  agentInstructionsFileNameV1,
  agentInstructionsFileStateV1,
  agentInstructionsGetResponsePayloadV1,
  agentInstructionsSetRequestPayloadV1,
  agentInstructionsSetResponsePayloadV1,
  agentInstructionsGetRequest,
  agentInstructionsGetResponse,
  agentInstructionsSetRequest,
  agentInstructionsSetResponse,
  ciAutoIterateStopReasonV1,
  ciAutoIterateAttemptV1,
  ciAutoIterateStateV1,
  ciAutoIterateStatusPayloadV1,
  ciAutoIterateStatus,
  ciAutoIterateStop,
  gitGraphRefKindV1,
  gitGraphRefV1,
  gitGraphCommitV1,
  gitGraphRequestPayloadV1,
  gitGraphResponsePayloadV1,
  gitGraphRequest,
  gitGraphResponse,
  runStatusEntryV1,
  runStatusOverallStateV1,
  runStatusStateV1,
  runStatusPayloadV1,
  runStatus,
} as const;
