import { argv } from 'node:process';
import { pathToFileURL } from 'node:url';

import { loadNodeConfig, type LoadNodeConfigOptions } from './config';
import { NodeIdentityStore } from './identity';
import { createNode, type NodeDaemon } from './node-daemon';
import { DEFAULT_LOCAL_TARGET } from './target';
import type { WebSocketConstructor } from './relay-connection';

export interface StartOptions extends LoadNodeConfigOptions {
  /** Test-only: overrides the global `WebSocket` `NodeDaemon` connects with. Never set in production. */
  webSocketImpl?: WebSocketConstructor;
}

export interface StartedNode {
  node: NodeDaemon;
  nodeId: string;
  /** This node's stable E2E device public key (base64), as reused/generated by `identity.ts`'s `NodeIdentityStore` (issue #64) — the same value across restarts as long as `stateDir` (and thus the persisted identity file) doesn't change. */
  devicePublicKey: string;
  /**
   * Closes the relay connection and every session's agent, once. Safe to
   * call more than once (subsequent calls are a no-op) — matters because
   * both a delivered signal and a caller's own cleanup path may race to call
   * it.
   */
  stop: () => Promise<void>;
}

/**
 * Runnable entry point for a v1 node daemon (SPEC §5.1; issue #63): loads
 * config from env/an optional file ({@link loadNodeConfig}), reuses this
 * node's persisted E2E identity keypair (`identity.ts`'s `NodeIdentityStore`,
 * issue #64 — generated on first run, reloaded on every restart after),
 * builds a `NodeDaemon`, and connects it to the relay. Mirrors
 * `packages/relay/src/main.ts`'s shape (a plain async `start()`, guarded by
 * the same `isMainModule` check below).
 *
 * Never hardcodes a secret: every credential (`authToken`, the AMK) comes
 * from `loadNodeConfig`, which itself only ever reads env vars or a config
 * file the operator provides.
 */
export async function start(options: StartOptions = {}): Promise<StartedNode> {
  const config = loadNodeConfig(options);

  const identityStore = new NodeIdentityStore({ stateDir: config.stateDir });
  const identity = await identityStore.loadOrCreate();

  const node = createNode({
    relayUrl: config.relayUrl,
    nodeId: config.nodeId,
    deviceId: config.deviceId,
    devicePublicKey: identity.publicKeyBase64,
    authToken: config.authToken,
    accountId: config.accountId,
    amk: config.amk,
    targets: config.targets,
    sshTargets: config.sshTargets,
    webSocketImpl: options.webSocketImpl,
  });

  const targetIds = (config.targets ?? [DEFAULT_LOCAL_TARGET]).map((target) => target.id);
  console.log(
    `loombox node "${config.nodeId}": connecting to ${config.relayUrl} (targets: ${targetIds.join(', ')})`,
  );
  node.on('connected', () => {
    console.log(`loombox node "${config.nodeId}": connected`);
  });

  let stopped = false;
  const stop = async (): Promise<void> => {
    if (stopped) return;
    stopped = true;
    console.log(`loombox node "${config.nodeId}": shutting down`);
    node.close();
  };

  return { node, nodeId: config.nodeId, devicePublicKey: identity.publicKeyBase64, stop };
}

export interface GracefulShutdownOptions {
  /** Defaults to `['SIGTERM', 'SIGINT']`. */
  signals?: NodeJS.Signals[];
  /**
   * If `stop()` hasn't settled within this many ms, force-exit with code 1
   * rather than hang forever on a wedged close path. The timer is
   * `unref()`'d, so it never itself keeps the process alive. Defaults to
   * 5000.
   */
  forceExitAfterMs?: number;
}

/**
 * Wires `signals` (SIGTERM/SIGINT by default) to `stop`, so a delivered
 * signal closes the relay connection and every session's agent before the
 * process exits (issue #63's "SIGTERM/SIGINT triggers a graceful
 * shutdown"). Deliberately never calls `process.exit()` on the happy path:
 * once `stop()` resolves (`NodeDaemon.close()` clears every timer and closes
 * every socket), nothing keeps the event loop alive and Node exits on its
 * own — an explicit `exit()` risks cutting off any not-yet-flushed I/O.
 * `forceExitAfterMs` is only a backstop for a `stop()` that never settles.
 */
export function installGracefulShutdown(
  stop: () => Promise<void>,
  options: GracefulShutdownOptions = {},
): void {
  const signals = options.signals ?? ['SIGTERM', 'SIGINT'];
  const forceExitAfterMs = options.forceExitAfterMs ?? 5000;

  for (const signal of signals) {
    process.once(signal, () => {
      console.log(`loombox node: received ${signal}, shutting down gracefully`);
      const forceExitTimer = setTimeout(() => {
        console.error('loombox node: graceful shutdown timed out; forcing exit');
        process.exit(1);
      }, forceExitAfterMs);
      forceExitTimer.unref();

      stop()
        .then(() => clearTimeout(forceExitTimer))
        .catch((error: unknown) => {
          clearTimeout(forceExitTimer);
          console.error('loombox node: error during shutdown', error);
          process.exitCode = 1;
        });
    });
  }
}

/** `start()` plus signal wiring — what actually runs when this module is executed directly (see the `isMainModule` guard below). */
export async function run(options: StartOptions = {}): Promise<StartedNode> {
  const started = await start(options);
  installGracefulShutdown(started.stop);
  return started;
}

const isMainModule = argv[1] !== undefined && import.meta.url === pathToFileURL(argv[1]).href;
if (isMainModule) {
  run().catch((error: unknown) => {
    console.error('loombox node failed to start', error);
    process.exitCode = 1;
  });
}
